#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun May 18 16:30:19 CST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=Bliss-Shader-main.zip
enableShaders=false
